In [27]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [2]:
df= pd.read_csv("Data\StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [5]:
x = df.drop(["math score"], axis=1)
x.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [6]:
y= df["math score"]
y.head()

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

In [24]:
y.shape

(1000,)

In [7]:
num_features = x.select_dtypes(include=[np.number]).columns
cat_features = x.select_dtypes(include=[object]).columns

In [8]:
num_features

Index(['reading score', 'writing score'], dtype='str')

In [13]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [21]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
le= OneHotEncoder()
s= StandardScaler()

In [22]:
preprocessing= ColumnTransformer(
    [
        ("one_hot_encoder", le, cat_features),
        ("standard_scaler", s,  num_features),
    ]
)

In [23]:
x= preprocessing.fit_transform(x)
x

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]], shape=(1000, 19))

In [25]:
x.shape

(1000, 19)

In [26]:
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size= 0.2, random_state= 42)
x_train.shape, x_test.shape

((800, 19), (200, 19))

In [28]:
def evaluation(actual, predicted):
    mse= mean_squared_error(actual, predicted)
    mae= mean_absolute_error(actual, predicted)
    r2 = r2_score(actual, predicted)
    
    return mse, mae, r2

In [31]:
models= {
    "Linear_regression": LinearRegression(),
    "lasso": Lasso(),
    "Ridge": Ridge(),
    'KNeighborsRegressor': KNeighborsRegressor(),
    "DecisionTree": DecisionTreeRegressor(),
    "RandomForestRegressor" : RandomForestRegressor(),
    "xgboost": XGBRegressor(),
    "catboost": CatBoostRegressor(),
    "Adaboost": AdaBoostRegressor()
    
}


model_list= []
r2_list= []


for i in range(len(list(models))):
    model= list(models.values())[i]
    model.fit(x_train, y_train)
    
    # predictions
    pred = model.predict(x_test)
    
    # Evaluation
    mse, mae, r2 = evaluation(y_test, pred)
    
    
    print(list(models.keys())[i])
    
    print("Model performance for Test")
    
    print(f"Mean Squared Error:{mse:2f}")
    print(f"Mean Absolute Error: {mae:2f}")
    print(f"R2 Score: {r2:2f}")
    print("="*50)  
    
    r2_list.append(r2)
    model_list.append(list(models.keys())[i])

Linear_regression
Model performance for Test
Mean Squared Error:29.095170
Mean Absolute Error: 4.214763
R2 Score: 0.880433
==================================================
lasso
Model performance for Test
Mean Squared Error:42.506417
Mean Absolute Error: 5.157882
R2 Score: 0.825320
==================================================
Ridge
Model performance for Test
Mean Squared Error:29.056272
Mean Absolute Error: 4.211101
R2 Score: 0.880593
==================================================
KNeighborsRegressor
Model performance for Test
Mean Squared Error:52.606600
Mean Absolute Error: 5.621000
R2 Score: 0.783813
==================================================
DecisionTree
Model performance for Test
Mean Squared Error:65.925000
Mean Absolute Error: 6.445000
R2 Score: 0.729081
==================================================
RandomForestRegressor
Model performance for Test
Mean Squared Error:37.548903
Mean Absolute Error: 4.703779
R2 Score: 0.845693
==================================================
xgboost
Model performance for Test
Mean Squared Error:41.903706
Mean Absolute Error: 5.057731
R2 Score: 0.827797
==================================================
Learning rate set to 0.039525
0:	learn: 14.5987177	total: 1.45ms	remaining: 1.45s
1:	learn: 14.2251886	total: 2.71ms	remaining: 1.35s
2:	learn: 13.8866124	total: 3.91ms	remaining: 1.3s
3:	learn: 13.5235688	total: 5.2ms	remaining: 1.29s
4:	learn: 13.1887021	total: 6.49ms	remaining: 1.29s
5:	learn: 12.9124226	total: 7.78ms	remaining: 1.29s
6:	learn: 12.6000335	total: 9.09ms	remaining: 1.29s
7:	learn: 12.3299057	total: 11.4ms	remaining: 1.41s
8:	learn: 12.0660619	total: 12.8ms	remaining: 1.41s
9:	learn: 11.7730981	total: 14ms	remaining: 1.39s
10:	learn: 11.4922764	total: 15.3ms	remaining: 1.37s
11:	learn: 11.2626483	total: 16.5ms	remaining: 1.35s
12:	learn: 11.0426039	total: 17.7ms	remaining: 1.34s
13:	learn: 10.7991693	total: 18.9ms	remaining: 1.33s
14:	learn: 10.5541002	total: 20.2ms	remaining: 1.32s
15:	learn: 10.3191811	total: 21.4ms	remaining: 1.31s
16:	learn: 10.1000444	total: 22.6ms	remaining: 1.31s
17:	learn: 9.8945567	total: 24.1ms	remaining: 1.31s
18:	learn: 9.6901741	total: 25.3ms	remaining: 1.31s
19:	learn: 9.5060349	total: 26.7ms	remaining: 1.31s
20:	learn: 9.3385246	total: 28ms	remaining: 1.3s
21:	learn: 9.1702033	total: 29.6ms	remaining: 1.31s
22:	learn: 9.0103000	total: 30.9ms	remaining: 1.31s
23:	learn: 8.8438667	total: 32.1ms	remaining: 1.3s
24:	learn: 8.6905481	total: 33.3ms	remaining: 1.3s
25:	learn: 8.5553077	total: 34.4ms	remaining: 1.29s
26:	learn: 8.4138513	total: 35.7ms	remaining: 1.28s
27:	learn: 8.2925602	total: 36.8ms	remaining: 1.28s
28:	learn: 8.1621938	total: 38.1ms	remaining: 1.27s
29:	learn: 8.0407363	total: 39.4ms	remaining: 1.27s
30:	learn: 7.9212203	total: 40.8ms	remaining: 1.27s
31:	learn: 7.8095890	total: 42.1ms	remaining: 1.27s
32:	learn: 7.6996758	total: 43.4ms	remaining: 1.27s
33:	learn: 7.6064527	total: 44.6ms	remaining: 1.27s
34:	learn: 7.4988803	total: 45.8ms	remaining: 1.26s
35:	learn: 7.4011587	total: 47.2ms	remaining: 1.26s
36:	learn: 7.3064311	total: 48.4ms	remaining: 1.26s
37:	learn: 7.2238635	total: 49.7ms	remaining: 1.26s
38:	learn: 7.1434777	total: 50.9ms	remaining: 1.25s
39:	learn: 7.0628171	total: 52.3ms	remaining: 1.25s
40:	learn: 6.9907934	total: 53.7ms	remaining: 1.25s
41:	learn: 6.9318622	total: 55ms	remaining: 1.25s
42:	learn: 6.8582966	total: 56.2ms	remaining: 1.25s
43:	learn: 6.7862682	total: 57.7ms	remaining: 1.25s
44:	learn: 6.7171185	total: 58.8ms	remaining: 1.25s
45:	learn: 6.6529481	total: 60ms	remaining: 1.24s
46:	learn: 6.5896861	total: 61.2ms	remaining: 1.24s
47:	learn: 6.5312831	total: 62.3ms	remaining: 1.24s
48:	learn: 6.4713680	total: 63.5ms	remaining: 1.23s
49:	learn: 6.4164814	total: 64.7ms	remaining: 1.23s
50:	learn: 6.3698708	total: 65.8ms	remaining: 1.23s
51:	learn: 6.3256781	total: 67.1ms	remaining: 1.22s
52:	learn: 6.2757661	total: 68.3ms	remaining: 1.22s
53:	learn: 6.2247740	total: 69.5ms	remaining: 1.22s
54:	learn: 6.1822493	total: 70.7ms	remaining: 1.21s
55:	learn: 6.1399042	total: 71.9ms	remaining: 1.21s
56:	learn: 6.1005255	total: 73ms	remaining: 1.21s
57:	learn: 6.0625686	total: 74.1ms	remaining: 1.2s
58:	learn: 6.0305593	total: 75.2ms	remaining: 1.2s
59:	learn: 5.9979314	total: 76.3ms	remaining: 1.2s
60:	learn: 5.9641038	total: 77.4ms	remaining: 1.19s
61:	learn: 5.9337297	total: 78.5ms	remaining: 1.19s
62:	learn: 5.9019327	total: 79.7ms	remaining: 1.18s
63:	learn: 5.8737278	total: 80.9ms	remaining: 1.18s
64:	learn: 5.8464857	total: 82.1ms	remaining: 1.18s
65:	learn: 5.8206309	total: 83.3ms	remaining: 1.18s
66:	learn: 5.7936462	total: 84.4ms	remaining: 1.18s
67:	learn: 5.7653886	total: 85.5ms	remaining: 1.17s
68:	learn: 5.7470739	total: 86.7ms	remaining: 1.17s
69:	learn: 5.7223152	total: 87.8ms	remaining: 1.17s
70:	learn: 5.6999706	total: 88.9ms	remaining: 1.16s
71:	learn: 5.6827326	total: 90ms	remaining: 1.16s
72:	learn: 5.6635258	total: 91.2ms	remaining: 1.16s
73:	learn: 5.6423816	total: 92.3ms	remaining: 1.15s
74:	learn: 5.6214048	total: 93.4ms	remaining: 1.15s
75:	learn: 5.6024601	total: 94.5ms	remaining: 1.15s
76:	learn: 5.5873376	total: 95.6ms	remaining: 1.15s
77:	learn: 5.5723930	total: 96.9ms	remaining: 1.15s
78:	learn: 5.5584258	total: 98ms	remaining: 1.14s
79:	learn: 5.5415189	total: 99.2ms	remaining: 1.14s
80:	learn: 5.5261573	total: 100ms	remaining: 1.14s
81:	learn: 5.5117470	total: 101ms	remaining: 1.13s
82:	learn: 5.5049750	total: 102ms	remaining: 1.13s
83:	learn: 5.4939805	total: 103ms	remaining: 1.12s
84:	learn: 5.4807455	total: 104ms	remaining: 1.12s
85:	learn: 5.4640520	total: 105ms	remaining: 1.12s
86:	learn: 5.4491437	total: 106ms	remaining: 1.12s
87:	learn: 5.4382554	total: 108ms	remaining: 1.11s
88:	learn: 5.4259279	total: 109ms	remaining: 1.11s
89:	learn: 5.4123312	total: 110ms	remaining: 1.11s
90:	learn: 5.4006915	total: 111ms	remaining: 1.11s
91:	learn: 5.3916187	total: 112ms	remaining: 1.11s
92:	learn: 5.3807666	total: 113ms	remaining: 1.11s
93:	learn: 5.3722072	total: 115ms	remaining: 1.1s
94:	learn: 5.3629188	total: 116ms	remaining: 1.1s
95:	learn: 5.3482923	total: 117ms	remaining: 1.1s
96:	learn: 5.3397723	total: 118ms	remaining: 1.1s
97:	learn: 5.3315160	total: 119ms	remaining: 1.09s
98:	learn: 5.3238616	total: 120ms	remaining: 1.09s
99:	learn: 5.3132773	total: 121ms	remaining: 1.09s
100:	learn: 5.3068563	total: 122ms	remaining: 1.09s
101:	learn: 5.2965206	total: 123ms	remaining: 1.08s
102:	learn: 5.2883508	total: 124ms	remaining: 1.08s
103:	learn: 5.2799335	total: 126ms	remaining: 1.08s
104:	learn: 5.2717891	total: 127ms	remaining: 1.08s
105:	learn: 5.2626847	total: 128ms	remaining: 1.08s
106:	learn: 5.2516198	total: 129ms	remaining: 1.08s
107:	learn: 5.2410122	total: 130ms	remaining: 1.07s
108:	learn: 5.2326840	total: 131ms	remaining: 1.07s
109:	learn: 5.2242671	total: 133ms	remaining: 1.07s
110:	learn: 5.2163250	total: 134ms	remaining: 1.07s
111:	learn: 5.2111025	total: 135ms	remaining: 1.07s
112:	learn: 5.2063643	total: 136ms	remaining: 1.07s
113:	learn: 5.1969376	total: 137ms	remaining: 1.07s
114:	learn: 5.1907460	total: 138ms	remaining: 1.06s
115:	learn: 5.1818852	total: 140ms	remaining: 1.06s
116:	learn: 5.1782936	total: 141ms	remaining: 1.06s
117:	learn: 5.1709914	total: 142ms	remaining: 1.06s
118:	learn: 5.1662572	total: 143ms	remaining: 1.06s
119:	learn: 5.1614212	total: 144ms	remaining: 1.05s
120:	learn: 5.1582235	total: 145ms	remaining: 1.05s
121:	learn: 5.1547099	total: 146ms	remaining: 1.05s
122:	learn: 5.1463881	total: 147ms	remaining: 1.05s
123:	learn: 5.1395294	total: 148ms	remaining: 1.05s
124:	learn: 5.1342760	total: 149ms	remaining: 1.04s
125:	learn: 5.1285361	total: 151ms	remaining: 1.04s
126:	learn: 5.1233004	total: 151ms	remaining: 1.04s
127:	learn: 5.1162005	total: 153ms	remaining: 1.04s
128:	learn: 5.1087287	total: 154ms	remaining: 1.04s
129:	learn: 5.1040759	total: 155ms	remaining: 1.04s
130:	learn: 5.1003176	total: 156ms	remaining: 1.03s
131:	learn: 5.0958142	total: 157ms	remaining: 1.03s
132:	learn: 5.0921469	total: 158ms	remaining: 1.03s
133:	learn: 5.0852583	total: 159ms	remaining: 1.03s
134:	learn: 5.0792194	total: 160ms	remaining: 1.03s
135:	learn: 5.0764768	total: 161ms	remaining: 1.02s
136:	learn: 5.0721339	total: 163ms	remaining: 1.03s
137:	learn: 5.0670316	total: 164ms	remaining: 1.02s
138:	learn: 5.0613583	total: 165ms	remaining: 1.02s
139:	learn: 5.0567591	total: 166ms	remaining: 1.02s
140:	learn: 5.0502540	total: 167ms	remaining: 1.02s
141:	learn: 5.0483765	total: 168ms	remaining: 1.02s
142:	learn: 5.0426038	total: 169ms	remaining: 1.01s
143:	learn: 5.0374773	total: 171ms	remaining: 1.01s
144:	learn: 5.0323049	total: 172ms	remaining: 1.01s
145:	learn: 5.0259762	total: 173ms	remaining: 1.01s
146:	learn: 5.0195245	total: 174ms	remaining: 1.01s
147:	learn: 5.0175694	total: 175ms	remaining: 1.01s
148:	learn: 5.0089624	total: 176ms	remaining: 1s
149:	learn: 5.0038803	total: 177ms	remaining: 1s
150:	learn: 4.9963876	total: 178ms	remaining: 1s
151:	learn: 4.9933617	total: 179ms	remaining: 1s
152:	learn: 4.9900575	total: 180ms	remaining: 999ms
153:	learn: 4.9869088	total: 181ms	remaining: 997ms
154:	learn: 4.9852072	total: 183ms	remaining: 995ms
155:	learn: 4.9790035	total: 184ms	remaining: 994ms
156:	learn: 4.9731422	total: 185ms	remaining: 994ms
157:	learn: 4.9670567	total: 186ms	remaining: 992ms
158:	learn: 4.9614607	total: 187ms	remaining: 991ms
159:	learn: 4.9542404	total: 188ms	remaining: 989ms
160:	learn: 4.9523207	total: 189ms	remaining: 986ms
161:	learn: 4.9483378	total: 190ms	remaining: 984ms
162:	learn: 4.9432286	total: 191ms	remaining: 982ms
163:	learn: 4.9385458	total: 193ms	remaining: 984ms
164:	learn: 4.9353306	total: 194ms	remaining: 983ms
165:	learn: 4.9320515	total: 195ms	remaining: 981ms
166:	learn: 4.9289642	total: 196ms	remaining: 979ms
167:	learn: 4.9228602	total: 198ms	remaining: 979ms
168:	learn: 4.9176688	total: 199ms	remaining: 979ms
169:	learn: 4.9103654	total: 200ms	remaining: 978ms
170:	learn: 4.9064572	total: 201ms	remaining: 977ms
171:	learn: 4.9019965	total: 203ms	remaining: 975ms
172:	learn: 4.8968162	total: 204ms	remaining: 974ms
173:	learn: 4.8911231	total: 205ms	remaining: 972ms
174:	learn: 4.8876302	total: 206ms	remaining: 970ms
175:	learn: 4.8852597	total: 207ms	remaining: 969ms
176:	learn: 4.8806597	total: 208ms	remaining: 967ms
177:	learn: 4.8772997	total: 209ms	remaining: 966ms
178:	learn: 4.8740388	total: 210ms	remaining: 965ms
179:	learn: 4.8694370	total: 212ms	remaining: 965ms
180:	learn: 4.8612687	total: 213ms	remaining: 965ms
181:	learn: 4.8586731	total: 214ms	remaining: 964ms
182:	learn: 4.8540362	total: 216ms	remaining: 963ms
183:	learn: 4.8513024	total: 217ms	remaining: 963ms
184:	learn: 4.8475101	total: 218ms	remaining: 961ms
185:	learn: 4.8456917	total: 219ms	remaining: 960ms
186:	learn: 4.8420586	total: 220ms	remaining: 958ms
187:	learn: 4.8386237	total: 221ms	remaining: 956ms
188:	learn: 4.8346022	total: 223ms	remaining: 955ms
189:	learn: 4.8308590	total: 224ms	remaining: 953ms
190:	learn: 4.8275905	total: 225ms	remaining: 952ms
191:	learn: 4.8222462	total: 226ms	remaining: 950ms
192:	learn: 4.8166864	total: 227ms	remaining: 949ms
193:	learn: 4.8147971	total: 228ms	remaining: 948ms
194:	learn: 4.8116394	total: 229ms	remaining: 947ms
195:	learn: 4.8048134	total: 231ms	remaining: 946ms
196:	learn: 4.8025161	total: 232ms	remaining: 944ms
197:	learn: 4.8000879	total: 233ms	remaining: 942ms
198:	learn: 4.7947731	total: 234ms	remaining: 941ms
199:	learn: 4.7916648	total: 235ms	remaining: 939ms
200:	learn: 4.7859899	total: 236ms	remaining: 938ms
201:	learn: 4.7823871	total: 237ms	remaining: 936ms
202:	learn: 4.7786237	total: 238ms	remaining: 935ms
203:	learn: 4.7757722	total: 239ms	remaining: 933ms
204:	learn: 4.7702310	total: 240ms	remaining: 932ms
205:	learn: 4.7644967	total: 242ms	remaining: 931ms
206:	learn: 4.7631387	total: 243ms	remaining: 930ms
207:	learn: 4.7580533	total: 244ms	remaining: 929ms
208:	learn: 4.7550638	total: 245ms	remaining: 928ms
209:	learn: 4.7524653	total: 246ms	remaining: 926ms
210:	learn: 4.7480674	total: 247ms	remaining: 925ms
211:	learn: 4.7441633	total: 248ms	remaining: 923ms
212:	learn: 4.7366709	total: 250ms	remaining: 922ms
213:	learn: 4.7334926	total: 251ms	remaining: 921ms
214:	learn: 4.7318646	total: 252ms	remaining: 919ms
215:	learn: 4.7283983	total: 253ms	remaining: 918ms
216:	learn: 4.7238660	total: 254ms	remaining: 916ms
217:	learn: 4.7234834	total: 255ms	remaining: 915ms
218:	learn: 4.7209542	total: 256ms	remaining: 914ms
219:	learn: 4.7161734	total: 257ms	remaining: 912ms
220:	learn: 4.7105640	total: 258ms	remaining: 911ms
221:	learn: 4.7071603	total: 259ms	remaining: 909ms
222:	learn: 4.7040835	total: 261ms	remaining: 908ms
223:	learn: 4.7025018	total: 262ms	remaining: 906ms
224:	learn: 4.7002697	total: 263ms	remaining: 905ms
225:	learn: 4.6953463	total: 264ms	remaining: 904ms
226:	learn: 4.6897693	total: 265ms	remaining: 903ms
227:	learn: 4.6879195	total: 266ms	remaining: 902ms
228:	learn: 4.6829821	total: 267ms	remaining: 900ms
229:	learn: 4.6795787	total: 269ms	remaining: 899ms
230:	learn: 4.6757514	total: 270ms	remaining: 898ms
231:	learn: 4.6727107	total: 271ms	remaining: 896ms
232:	learn: 4.6690533	total: 272ms	remaining: 896ms
233:	learn: 4.6675957	total: 273ms	remaining: 895ms
234:	learn: 4.6642413	total: 274ms	remaining: 894ms
235:	learn: 4.6622470	total: 276ms	remaining: 892ms
236:	learn: 4.6586684	total: 277ms	remaining: 891ms
237:	learn: 4.6580176	total: 278ms	remaining: 889ms
238:	learn: 4.6576567	total: 279ms	remaining: 888ms
239:	learn: 4.6532429	total: 280ms	remaining: 886ms
240:	learn: 4.6507302	total: 281ms	remaining: 885ms
241:	learn: 4.6476713	total: 282ms	remaining: 883ms
242:	learn: 4.6455060	total: 283ms	remaining: 882ms
243:	learn: 4.6412979	total: 284ms	remaining: 881ms
244:	learn: 4.6379811	total: 285ms	remaining: 879ms
245:	learn: 4.6350623	total: 286ms	remaining: 878ms
246:	learn: 4.6316060	total: 288ms	remaining: 877ms
247:	learn: 4.6302155	total: 289ms	remaining: 875ms
248:	learn: 4.6272981	total: 290ms	remaining: 874ms
249:	learn: 4.6246918	total: 291ms	remaining: 872ms
250:	learn: 4.6218401	total: 292ms	remaining: 871ms
251:	learn: 4.6196021	total: 293ms	remaining: 869ms
252:	learn: 4.6135840	total: 294ms	remaining: 868ms
253:	learn: 4.6119388	total: 295ms	remaining: 867ms
254:	learn: 4.6087070	total: 296ms	remaining: 865ms
255:	learn: 4.6047716	total: 297ms	remaining: 864ms
256:	learn: 4.6042313	total: 298ms	remaining: 862ms
257:	learn: 4.6007504	total: 300ms	remaining: 861ms
258:	learn: 4.5964883	total: 301ms	remaining: 860ms
259:	learn: 4.5947078	total: 302ms	remaining: 859ms
260:	learn: 4.5888180	total: 303ms	remaining: 858ms
261:	learn: 4.5850542	total: 304ms	remaining: 856ms
262:	learn: 4.5814714	total: 305ms	remaining: 855ms
263:	learn: 4.5775552	total: 306ms	remaining: 854ms
264:	learn: 4.5745714	total: 307ms	remaining: 852ms
265:	learn: 4.5730292	total: 308ms	remaining: 851ms
266:	learn: 4.5713262	total: 309ms	remaining: 850ms
267:	learn: 4.5710192	total: 310ms	remaining: 848ms
268:	learn: 4.5657666	total: 312ms	remaining: 847ms
269:	learn: 4.5633835	total: 313ms	remaining: 845ms
270:	learn: 4.5581658	total: 314ms	remaining: 844ms
271:	learn: 4.5562921	total: 315ms	remaining: 843ms
272:	learn: 4.5493838	total: 316ms	remaining: 841ms
273:	learn: 4.5462275	total: 317ms	remaining: 840ms
274:	learn: 4.5406210	total: 318ms	remaining: 839ms
275:	learn: 4.5328982	total: 319ms	remaining: 837ms
276:	learn: 4.5297574	total: 320ms	remaining: 836ms
277:	learn: 4.5257929	total: 321ms	remaining: 835ms
278:	learn: 4.5215722	total: 322ms	remaining: 833ms
279:	learn: 4.5188181	total: 324ms	remaining: 832ms
280:	learn: 4.5140123	total: 325ms	remaining: 831ms
281:	learn: 4.5083314	total: 326ms	remaining: 830ms
282:	learn: 4.5060385	total: 327ms	remaining: 829ms
283:	learn: 4.5058056	total: 328ms	remaining: 828ms
284:	learn: 4.5015504	total: 329ms	remaining: 827ms
285:	learn: 4.4946926	total: 331ms	remaining: 825ms
286:	learn: 4.4893302	total: 332ms	remaining: 824ms
287:	learn: 4.4848270	total: 333ms	remaining: 823ms
288:	learn: 4.4782854	total: 334ms	remaining: 822ms
289:	learn: 4.4753117	total: 335ms	remaining: 821ms
290:	learn: 4.4715813	total: 336ms	remaining: 819ms
291:	learn: 4.4691650	total: 337ms	remaining: 818ms
292:	learn: 4.4620680	total: 339ms	remaining: 817ms
293:	learn: 4.4585410	total: 340ms	remaining: 816ms
294:	learn: 4.4557575	total: 341ms	remaining: 814ms
295:	learn: 4.4530274	total: 342ms	remaining: 813ms
296:	learn: 4.4506593	total: 343ms	remaining: 812ms
297:	learn: 4.4446969	total: 344ms	remaining: 811ms
298:	learn: 4.4420528	total: 345ms	remaining: 810ms
299:	learn: 4.4400368	total: 346ms	remaining: 808ms
300:	learn: 4.4350171	total: 348ms	remaining: 807ms
301:	learn: 4.4299621	total: 349ms	remaining: 806ms
302:	learn: 4.4276663	total: 350ms	remaining: 805ms
303:	learn: 4.4250300	total: 351ms	remaining: 803ms
304:	learn: 4.4225888	total: 352ms	remaining: 802ms
305:	learn: 4.4189367	total: 353ms	remaining: 801ms
306:	learn: 4.4168880	total: 354ms	remaining: 799ms
307:	learn: 4.4137734	total: 355ms	remaining: 798ms
308:	learn: 4.4111294	total: 356ms	remaining: 797ms
309:	learn: 4.4085082	total: 357ms	remaining: 796ms
310:	learn: 4.4048803	total: 359ms	remaining: 794ms
311:	learn: 4.4045938	total: 360ms	remaining: 793ms
312:	learn: 4.4021399	total: 361ms	remaining: 792ms
313:	learn: 4.4002847	total: 362ms	remaining: 790ms
314:	learn: 4.3958055	total: 363ms	remaining: 789ms
315:	learn: 4.3928388	total: 364ms	remaining: 788ms
316:	learn: 4.3892131	total: 365ms	remaining: 787ms
317:	learn: 4.3861981	total: 366ms	remaining: 785ms
318:	learn: 4.3850542	total: 367ms	remaining: 784ms
319:	learn: 4.3793646	total: 369ms	remaining: 784ms
320:	learn: 4.3783876	total: 370ms	remaining: 783ms
321:	learn: 4.3758167	total: 371ms	remaining: 782ms
322:	learn: 4.3746002	total: 373ms	remaining: 782ms
323:	learn: 4.3709890	total: 375ms	remaining: 781ms
324:	learn: 4.3674185	total: 376ms	remaining: 780ms
325:	learn: 4.3635846	total: 377ms	remaining: 779ms
326:	learn: 4.3607707	total: 378ms	remaining: 777ms
327:	learn: 4.3586758	total: 379ms	remaining: 776ms
328:	learn: 4.3542282	total: 380ms	remaining: 775ms
329:	learn: 4.3537734	total: 381ms	remaining: 773ms
330:	learn: 4.3516480	total: 382ms	remaining: 772ms
331:	learn: 4.3482099	total: 383ms	remaining: 771ms
332:	learn: 4.3458527	total: 384ms	remaining: 769ms
333:	learn: 4.3423734	total: 386ms	remaining: 769ms
334:	learn: 4.3408144	total: 387ms	remaining: 768ms
335:	learn: 4.3397071	total: 388ms	remaining: 767ms
336:	learn: 4.3354308	total: 389ms	remaining: 765ms
337:	learn: 4.3352189	total: 390ms	remaining: 764ms
338:	learn: 4.3285072	total: 391ms	remaining: 763ms
339:	learn: 4.3261407	total: 393ms	remaining: 762ms
340:	learn: 4.3237856	total: 394ms	remaining: 761ms
341:	learn: 4.3206325	total: 395ms	remaining: 760ms
342:	learn: 4.3197372	total: 396ms	remaining: 759ms
343:	learn: 4.3180009	total: 397ms	remaining: 757ms
344:	learn: 4.3127136	total: 398ms	remaining: 756ms
345:	learn: 4.3082208	total: 399ms	remaining: 755ms
346:	learn: 4.3058909	total: 400ms	remaining: 754ms
347:	learn: 4.3051379	total: 402ms	remaining: 752ms
348:	learn: 4.3047872	total: 403ms	remaining: 751ms
349:	learn: 4.3035013	total: 404ms	remaining: 750ms
350:	learn: 4.3029381	total: 405ms	remaining: 748ms
351:	learn: 4.2995485	total: 406ms	remaining: 747ms
352:	learn: 4.2947684	total: 407ms	remaining: 746ms
353:	learn: 4.2945815	total: 408ms	remaining: 744ms
354:	learn: 4.2925516	total: 409ms	remaining: 743ms
355:	learn: 4.2886289	total: 410ms	remaining: 742ms
356:	learn: 4.2878028	total: 411ms	remaining: 740ms
357:	learn: 4.2845669	total: 412ms	remaining: 739ms
358:	learn: 4.2789023	total: 413ms	remaining: 738ms
359:	learn: 4.2769380	total: 414ms	remaining: 737ms
360:	learn: 4.2734251	total: 416ms	remaining: 736ms
361:	learn: 4.2697265	total: 417ms	remaining: 734ms